version: '3.8'

services:
  m4-ecommerce:
    image: m4-ecommerce
    ports:
      - '3001:3000'
    env_file:
      - .env.docker.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.docker.development

volumes:
  pgdata:
